# Generated by Django 4.2.2 on 2023-07-18 12:06

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(help_text='Overwrites the default title', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(help_text='Overwrites the default title', max_length=100, null=True)),
                ('contenu', wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='entrez un titre', required=True)), ('text', wagtail.blocks.TextBlock(help_text='entrez un texte', required=True))])), ('full_richtext', streams.blocks.RichText()), ('card_service', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='entrez un titre', required=True)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('titre', wagtail.blocks.CharBlock(max_length='100', required=True)), ('text', wagtail.blocks.CharBlock(max_length='400', required=True)), ('date', wagtail.blocks.DateBlock(required=True)), ('boutonI', wagtail.blocks.PageChooserBlock(required=False)), ('boutonE', wagtail.blocks.URLBlock(required=False))])))])), ('CTA', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(max_length='100', required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('boutonIn', wagtail.blocks.PageChooserBlock(required=False)), ('boutonUrl', wagtail.blocks.URLBlock(required=False)), ('boutonText', wagtail.blocks.CharBlock(max_length='400', required=True))]))], null=True, use_json_field=True)),
                ('blog_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
