# Generated by Django 4.2.2 on 2023-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='auteur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
