# Generated by Django 4.2.2 on 2023-07-12 09:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_banner_cta_alter_homepage_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('CTA', wagtail.blocks.StructBlock([('titre', wagtail.blocks.CharBlock(max_length='100', required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('boutonIn', wagtail.blocks.PageChooserBlock(required=False)), ('boutonUrl', wagtail.blocks.URLBlock(required=False)), ('boutonText', wagtail.blocks.CharBlock(max_length='400', required=True))]))], null=True, use_json_field=True),
        ),
    ]
