# Generated by Django 4.2.2 on 2023-07-10 10:20

from django.db import migrations
import wagtail.blocks   
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flex Page', 'verbose_name_plural': 'Flex Pages'},
        ),
        migrations.AddField(
            model_name='flexpage',
            name='contenu',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='entrez un titre', required=True)), ('text', wagtail.blocks.TextBlock(help_text='entrez un texte', required=True))]))], null=True, use_json_field=True),
        ),
    ]
